# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d7903a151a8d4d52419cd30c1ea19e03d9e1207df609eab62e05df65d1986a04cc638d570ac395c0aa705bcf6308daaacb31a3d0b58405d3f778af21fb86143

test:
  secret_key_base: a639449b028a560257dcca0c430fc5f003b6dece98300aafc7b4e96477b7a2ccec4cc3b2c2635a4ad13010fd35ece93005d813c718558bcf52073288ddb0445d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
